/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Acomplishments: typeof import('./src/components/acomplishments.vue')['default']
    Blog: typeof import('./src/components/blog.vue')['default']
    Cases: typeof import('./src/components/cases.vue')['default']
    Contact: typeof import('./src/components/contact.vue')['default']
    Email: typeof import('./src/components/email.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Project: typeof import('./src/components/project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/globle/sidebar/Sidebar.vue')['default']
    Skill: typeof import('./src/components/skill.vue')['default']
    TabsComponent: typeof import('./src/components/globle/tabs/TabsComponent.vue')['default']
    WebGLCanvas: typeof import('./src/components/webGL/WebGLCanvas.vue')['default']
  }
}
